import type { CandidateProfile } from "@/lib/types";

export const DEFAULT_PROFILE: CandidateProfile = {
  seniority: {
    preferred: ["Staff", "Lead"],
    acceptable: ["Senior"],
  },
  coreRoles: [
    "SRE",
    "Site Reliability Engineering",
    "Platform Engineering",
    "Infrastructure Engineering",
    "Cloud Architecture",
    "DevOps",
    "Production Engineering",
  ],
  cloud: ["AWS", "GCP", "OCI"],
  platform: [
    "Kubernetes",
    "Terraform",
    "Linux",
    "Distributed Systems",
    "Cloud Infrastructure",
    "Platform Architecture",
  ],
  ai: [
    "AI Infrastructure",
    "AI Platform",
    "LLM Infrastructure",
    "LLMOps",
    "ML Infrastructure",
    "MLOps",
    "Model Serving",
    "Inference",
    "GPU",
    "AI Observability",
  ],
  observability: [
    "OpenTelemetry",
    "Observability",
    "Monitoring",
    "Logging",
    "Tracing",
  ],
  preferredLocations: ["EU", "Europe", "Switzerland", "Japan", "Remote", "Pune"],
  preferredRemoteRegions: ["Europe", "EMEA", "Japan", "India", "Pune", "Worldwide"],
  negativeSignals: [
    "Junior",
    "Entry level",
    "Mid level",
    "Frontend",
    "Mobile",
    "Pure backend application development",
    "QA",
    "React",
    "Full-stack",
    "Fullstack",
    "Data Engineer",
    "Applied Scientist",
    "Product Analyst",
    "Program Manager",
    "Machine Learning Engineer",
    "Sales",
    "Support",
    "Helpdesk",
  ],
  searchTitles: [
    "Staff SRE",
    "Staff Site Reliability Engineer",
    "Staff Infrastructure Engineer",
    "Staff Platform Engineer",
    "Staff Platform Architect",
    "Staff Cloud Engineer",
    "Staff DevOps Engineer",
    "Senior Platform Engineer",
    "Senior SRE",
    "Senior Site Reliability Engineer",
    "Senior Staff Engineer",
    "Lead SRE",
    "Lead Platform Engineer",
    "Lead Infrastructure Engineer",
    "Cloud Architect",
    "Cloud Infrastructure Engineer",
    "AI Infrastructure Engineer",
    "AI Platform Engineer",
    "ML Infrastructure Engineer",
    "ML Platform Engineer",
    "LLM Infrastructure Engineer",
    "Inference Infrastructure Engineer",
    "Inference Engineer",
    "Compute Platform Engineer",
    "Production Engineer",
    "Reliability Engineer",
    "Infrastructure Technical Lead",
    "Software Engineer, Infrastructure",
    "Software Engineer - Infrastructure",
    "Software Engineer (Infrastructure)",
    "Staff Software Engineer (Infrastructure)",
    "Infrastructure Software Engineer",
    "Developer Platform Engineer",
    "Internal Platform Engineer",
    "Platform Software Engineer",
    "Core Infrastructure Engineer",
    "Foundations Engineer",
    "Technical Infrastructure Engineer",
    "Distributed Systems Engineer",
    "Kubernetes Engineer",
    "Container Platform Engineer",
    "Observability Engineer",
    "Telemetry Engineer",
    "Release Engineer",
    "Build Engineer",
    "Data Platform Engineer",
    "Network Platform Engineer",
    "Engineering Manager, SRE",
    "Engineering Manager, Platform",
    "Engineering Manager, Infrastructure",
  ],
  immigration: {
    primaryObjective: "EU visa-sponsored staff/senior infrastructure roles",
    preferredCountries: [
      "Germany",
      "Netherlands",
      "Ireland",
      "Sweden",
      "Denmark",
      "Finland",
      "Portugal",
      "Spain",
      "Poland",
      "Switzerland",
    ],
    secondaryCountries: [
      "United Kingdom",
      "Japan",
      "Singapore",
      "Canada",
      "Australia",
      "United Arab Emirates",
    ],
    requireVisaSupport: false,
    preferExplicitVisaSupport: true,
    rejectExistingWorkAuthorizationOnly: true,
    acceptUnknownVisaStatusAtScore: 0.62,
    acceptBareRemoteAtScore: 0.72,
    companySponsorBonus: 0.03,
    explicitVisaBonus: 0.12,
    relocationBonus: 0.06,
  },
};
